
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140808 (SVN rev 54)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EXPINT_LIT = 55;
  public static final int FLOAT_LIT = 53;
  public static final int LESS_TE = 46;
  public static final int CHAR_LIT = 57;
  public static final int SEP = 30;
  public static final int DOSPUNTOS = 31;
  public static final int POW = 37;
  public static final int MULT = 34;
  public static final int CHAR = 5;
  public static final int EMPTY = 8;
  public static final int CASE = 16;
  public static final int LLAVE_I = 23;
  public static final int INT = 3;
  public static final int LLAVE_D = 24;
  public static final int GREATER_TE = 48;
  public static final int MINUS = 33;
  public static final int NOT = 42;
  public static final int AND = 40;
  public static final int GREATER_T = 47;
  public static final int OR = 41;
  public static final int BOOL = 7;
  public static final int COMMA = 27;
  public static final int FRAC_LIT = 54;
  public static final int INC = 38;
  public static final int DIV = 35;
  public static final int PLUS = 32;
  public static final int ASSIGN = 29;
  public static final int MAIN = 11;
  public static final int IF = 12;
  public static final int ID = 51;
  public static final int EOF = 0;
  public static final int RETURN = 15;
  public static final int EQUAL = 43;
  public static final int TRUE = 49;
  public static final int PAR_I = 21;
  public static final int error = 1;
  public static final int PAR_D = 22;
  public static final int MOD = 36;
  public static final int CIN = 58;
  public static final int BREAK = 14;
  public static final int ARR_I = 25;
  public static final int SWITCH = 18;
  public static final int LEX_ERROR = 2;
  public static final int ARR_D = 26;
  public static final int ELSE = 13;
  public static final int COUT = 59;
  public static final int N_EQUAL = 44;
  public static final int WHILE = 19;
  public static final int DEFAULT = 17;
  public static final int FLOAT = 4;
  public static final int FRAC_KW = 10;
  public static final int STRING = 6;
  public static final int DEC = 39;
  public static final int EXPINT_KW = 9;
  public static final int FALSE = 50;
  public static final int LESS_T = 45;
  public static final int STRING_LIT = 56;
  public static final int INT_LIT = 52;
  public static final int DO = 20;
  public static final int PYC = 28;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LEX_ERROR",
  "INT",
  "FLOAT",
  "CHAR",
  "STRING",
  "BOOL",
  "EMPTY",
  "EXPINT_KW",
  "FRAC_KW",
  "MAIN",
  "IF",
  "ELSE",
  "BREAK",
  "RETURN",
  "CASE",
  "DEFAULT",
  "SWITCH",
  "WHILE",
  "DO",
  "PAR_I",
  "PAR_D",
  "LLAVE_I",
  "LLAVE_D",
  "ARR_I",
  "ARR_D",
  "COMMA",
  "PYC",
  "ASSIGN",
  "SEP",
  "DOSPUNTOS",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "MOD",
  "POW",
  "INC",
  "DEC",
  "AND",
  "OR",
  "NOT",
  "EQUAL",
  "N_EQUAL",
  "LESS_T",
  "LESS_TE",
  "GREATER_T",
  "GREATER_TE",
  "TRUE",
  "FALSE",
  "ID",
  "INT_LIT",
  "FLOAT_LIT",
  "FRAC_LIT",
  "EXPINT_LIT",
  "STRING_LIT",
  "CHAR_LIT",
  "CIN",
  "COUT"
  };
}

