// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/scanner/Lexer.flex

package scanner;

import parser.*;
import java_cup.runtime.Symbol;
import java.util.ArrayList;
import java.util.List;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.io.IOException;


@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\36\u0100\1\u0400\u1001\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\2\22\0\1\1"+
    "\1\5\1\6\1\7\1\10\1\11\1\0\1\12\2\0"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\11\22"+
    "\1\23\1\0\1\24\1\0\1\25\1\0\1\26\4\27"+
    "\1\30\1\31\15\27\1\32\6\27\1\0\1\33\1\0"+
    "\1\34\1\35\1\0\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\27\1\47\1\50\1\51"+
    "\1\52\1\53\1\54\1\55\1\56\1\57\1\60\1\61"+
    "\1\27\1\62\1\63\1\64\1\27\1\65\1\66\1\67"+
    "\1\70\6\0\1\3\33\0\1\71\u0186\0\2\3\326\0"+
    "\u0100\3\377\0\1\72";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1280];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\1\5\1\6"+
    "\1\1\1\7\1\10\1\11\1\12\1\13\2\14\1\15"+
    "\2\1\1\16\3\17\1\20\15\17\2\1\1\21\1\1"+
    "\1\22\1\0\1\23\3\0\1\24\1\25\3\0\1\26"+
    "\1\27\1\30\1\31\1\32\12\17\1\33\7\17\1\34"+
    "\7\17\1\0\1\35\1\36\1\2\1\37\1\40\1\41"+
    "\1\0\7\17\1\42\11\17\1\43\6\17\1\0\1\44"+
    "\1\17\1\45\1\17\1\46\1\17\1\47\1\50\1\51"+
    "\1\17\1\52\4\17\1\53\7\17\1\0\1\2\1\54"+
    "\2\17\1\55\1\17\1\56\1\57\1\17\1\60\6\17"+
    "\1\61\1\0\3\17\1\62\1\17\1\63\1\17\1\64"+
    "\1\65\1\66\1\2\1\17\1\46\1\67\1\17\1\70"+
    "\1\71\1\72\2\17\1\73\1\74";

  private static int [] zzUnpackAction() {
    int [] result = new int[180];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\73\0\166\0\73\0\261\0\73\0\73\0\73"+
    "\0\354\0\73\0\u0127\0\73\0\u0162\0\73\0\u019d\0\u01d8"+
    "\0\u0213\0\u024e\0\u0289\0\73\0\u02c4\0\u02ff\0\u033a\0\73"+
    "\0\u0375\0\u03b0\0\u03eb\0\u0426\0\u0461\0\u049c\0\u04d7\0\u0512"+
    "\0\u054d\0\u0588\0\u05c3\0\u05fe\0\u0639\0\u0674\0\u06af\0\73"+
    "\0\u06ea\0\73\0\261\0\73\0\u0725\0\u0760\0\u079b\0\73"+
    "\0\73\0\u07d6\0\u0811\0\u084c\0\73\0\73\0\73\0\73"+
    "\0\73\0\u0887\0\u08c2\0\u08fd\0\u0938\0\u0973\0\u09ae\0\u09e9"+
    "\0\u0a24\0\u0a5f\0\u0a9a\0\u02c4\0\u0ad5\0\u0b10\0\u0b4b\0\u0b86"+
    "\0\u0bc1\0\u0bfc\0\u0c37\0\u02c4\0\u0c72\0\u0cad\0\u0ce8\0\u0d23"+
    "\0\u0d5e\0\u0d99\0\u0dd4\0\u0e0f\0\73\0\73\0\u0e4a\0\73"+
    "\0\u07d6\0\u0e85\0\u0ec0\0\u0efb\0\u0f36\0\u0f71\0\u0fac\0\u0fe7"+
    "\0\u1022\0\u105d\0\u02c4\0\u1098\0\u10d3\0\u110e\0\u1149\0\u1184"+
    "\0\u11bf\0\u11fa\0\u1235\0\u1270\0\u02c4\0\u12ab\0\u12e6\0\u1321"+
    "\0\u135c\0\u1397\0\u13d2\0\u140d\0\u1448\0\u1483\0\u02c4\0\u14be"+
    "\0\u14f9\0\u1534\0\u02c4\0\u02c4\0\u02c4\0\u156f\0\u02c4\0\u15aa"+
    "\0\u15e5\0\u1620\0\u165b\0\u02c4\0\u1696\0\u16d1\0\u170c\0\u1747"+
    "\0\u1782\0\u17bd\0\u17f8\0\u1833\0\73\0\u02c4\0\u186e\0\u18a9"+
    "\0\u02c4\0\u18e4\0\u02c4\0\u02c4\0\u191f\0\u02c4\0\u195a\0\u1995"+
    "\0\u19d0\0\u1a0b\0\u1a46\0\u1a81\0\u02c4\0\u1abc\0\u1af7\0\u1b32"+
    "\0\u1b6d\0\u02c4\0\u1ba8\0\u1be3\0\u1c1e\0\u02c4\0\u02c4\0\u02c4"+
    "\0\u0e0f\0\u1c59\0\u02c4\0\u02c4\0\u1c94\0\u02c4\0\u02c4\0\u02c4"+
    "\0\u1ccf\0\u1d0a\0\u1d45\0\u02c4";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[180];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\2\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\2\25\1\26"+
    "\1\27\1\2\1\30\1\31\1\25\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\25\1\40\1\25\1\41\1\25"+
    "\1\42\3\25\1\43\1\44\2\25\1\45\2\25\1\46"+
    "\1\47\1\2\1\50\1\51\1\52\74\0\2\3\1\0"+
    "\1\3\66\0\2\53\1\0\3\53\1\54\24\53\1\55"+
    "\37\53\2\56\1\0\7\56\1\0\20\56\1\57\37\56"+
    "\14\0\1\60\74\0\1\61\3\0\1\20\67\0\1\62"+
    "\10\0\1\63\11\0\1\63\47\0\1\62\1\64\2\20"+
    "\5\0\1\63\11\0\1\63\116\0\1\65\22\0\1\66"+
    "\5\0\1\67\41\0\1\70\31\0\1\71\66\0\2\25"+
    "\4\0\4\25\2\0\30\25\27\0\2\25\4\0\4\25"+
    "\2\0\1\25\1\72\26\25\27\0\2\25\4\0\4\25"+
    "\2\0\21\25\1\73\6\25\27\0\2\25\4\0\4\25"+
    "\2\0\1\74\27\25\27\0\2\25\4\0\4\25\2\0"+
    "\16\25\1\75\2\25\1\76\6\25\27\0\2\25\4\0"+
    "\4\25\2\0\1\25\1\77\6\25\1\100\1\101\4\25"+
    "\1\102\11\25\27\0\2\25\4\0\4\25\2\0\5\25"+
    "\1\103\10\25\1\104\11\25\27\0\2\25\4\0\4\25"+
    "\2\0\13\25\1\105\1\106\3\25\1\107\5\25\1\110"+
    "\1\25\27\0\2\25\4\0\4\25\2\0\13\25\1\111"+
    "\5\25\1\112\6\25\27\0\2\25\4\0\4\25\2\0"+
    "\21\25\1\113\6\25\27\0\2\25\4\0\4\25\2\0"+
    "\6\25\1\114\6\25\1\115\12\25\27\0\2\25\4\0"+
    "\4\25\2\0\5\25\1\116\22\25\27\0\2\25\4\0"+
    "\4\25\2\0\1\117\27\25\27\0\2\25\4\0\4\25"+
    "\2\0\5\25\1\120\22\25\27\0\2\25\4\0\4\25"+
    "\2\0\23\25\1\121\1\25\1\122\2\25\27\0\2\25"+
    "\4\0\4\25\2\0\10\25\1\123\17\25\24\0\1\124"+
    "\77\0\1\125\1\0\1\126\136\0\1\127\1\0\2\53"+
    "\3\0\66\53\12\0\1\130\60\0\2\56\3\0\66\56"+
    "\21\0\2\131\72\0\1\132\70\0\1\133\73\0\2\25"+
    "\4\0\4\25\2\0\13\25\1\134\14\25\27\0\2\25"+
    "\4\0\4\25\2\0\24\25\1\135\3\25\27\0\2\25"+
    "\4\0\4\25\2\0\14\25\1\136\13\25\27\0\2\25"+
    "\4\0\4\25\2\0\16\25\1\137\11\25\27\0\2\25"+
    "\4\0\4\25\2\0\5\25\1\140\22\25\27\0\2\25"+
    "\4\0\4\25\2\0\22\25\1\141\5\25\27\0\2\25"+
    "\4\0\4\25\2\0\1\25\1\142\26\25\27\0\2\25"+
    "\4\0\4\25\2\0\15\25\1\143\12\25\27\0\2\25"+
    "\4\0\4\25\2\0\24\25\1\144\3\25\27\0\2\25"+
    "\4\0\4\25\2\0\6\25\1\145\21\25\27\0\2\25"+
    "\4\0\4\25\2\0\22\25\1\146\5\25\27\0\2\25"+
    "\4\0\4\25\2\0\17\25\1\147\10\25\27\0\2\25"+
    "\4\0\4\25\2\0\24\25\1\150\3\25\27\0\2\25"+
    "\4\0\4\25\2\0\17\25\1\151\10\25\27\0\2\25"+
    "\4\0\4\25\2\0\16\25\1\152\11\25\27\0\2\25"+
    "\4\0\4\25\2\0\1\25\1\153\26\25\27\0\2\25"+
    "\4\0\4\25\2\0\5\25\1\154\22\25\27\0\2\25"+
    "\4\0\4\25\2\0\23\25\1\155\4\25\27\0\2\25"+
    "\4\0\4\25\2\0\22\25\1\156\5\25\27\0\2\25"+
    "\4\0\4\25\2\0\5\25\1\157\22\25\27\0\2\25"+
    "\4\0\4\25\2\0\23\25\1\160\4\25\27\0\2\25"+
    "\4\0\4\25\2\0\21\25\1\161\6\25\27\0\2\25"+
    "\4\0\4\25\2\0\11\25\1\162\16\25\27\0\2\25"+
    "\4\0\4\25\2\0\11\25\1\163\16\25\6\0\16\124"+
    "\1\164\54\124\2\127\1\0\70\127\21\0\2\132\72\0"+
    "\1\165\71\0\2\25\4\0\4\25\2\0\22\25\1\166"+
    "\5\25\27\0\2\25\4\0\4\25\2\0\5\25\1\167"+
    "\22\25\27\0\2\25\4\0\4\25\2\0\1\25\1\170"+
    "\26\25\27\0\2\25\4\0\4\25\2\0\13\25\1\171"+
    "\14\25\27\0\2\25\4\0\4\25\2\0\1\25\1\172"+
    "\26\25\27\0\2\25\4\0\4\25\2\0\5\25\1\173"+
    "\22\25\27\0\2\25\4\0\4\25\2\0\21\25\1\174"+
    "\6\25\27\0\2\25\4\0\4\25\2\0\23\25\1\175"+
    "\4\25\27\0\2\25\4\0\4\25\2\0\1\25\1\176"+
    "\26\25\27\0\2\25\4\0\4\25\2\0\5\25\1\177"+
    "\22\25\27\0\2\25\4\0\4\25\2\0\23\25\1\200"+
    "\4\25\27\0\2\25\4\0\4\25\2\0\1\25\1\201"+
    "\26\25\27\0\2\25\4\0\4\25\2\0\11\25\1\202"+
    "\16\25\27\0\2\25\4\0\4\25\2\0\1\25\1\203"+
    "\26\25\27\0\2\25\4\0\4\25\2\0\3\25\1\204"+
    "\24\25\27\0\2\25\4\0\4\25\2\0\1\25\1\205"+
    "\26\25\27\0\2\25\4\0\4\25\2\0\22\25\1\206"+
    "\5\25\27\0\2\25\4\0\4\25\2\0\20\25\1\207"+
    "\7\25\27\0\2\25\4\0\4\25\2\0\24\25\1\210"+
    "\3\25\27\0\2\25\4\0\4\25\2\0\11\25\1\211"+
    "\16\25\27\0\2\25\4\0\4\25\2\0\23\25\1\212"+
    "\4\25\27\0\2\25\4\0\4\25\2\0\13\25\1\213"+
    "\14\25\6\0\16\124\1\214\50\124\1\215\3\124\21\0"+
    "\2\165\71\0\2\25\4\0\4\25\2\0\5\25\1\216"+
    "\22\25\27\0\2\25\4\0\4\25\2\0\11\25\1\217"+
    "\16\25\27\0\2\25\4\0\4\25\2\0\5\25\1\220"+
    "\22\25\27\0\2\25\4\0\4\25\2\0\12\25\1\221"+
    "\15\25\27\0\2\25\4\0\4\25\2\0\24\25\1\222"+
    "\3\25\27\0\2\25\4\0\4\25\2\0\27\25\1\223"+
    "\27\0\2\25\4\0\4\25\2\0\13\25\1\224\14\25"+
    "\27\0\2\25\4\0\4\25\2\0\15\25\1\225\12\25"+
    "\27\0\2\25\4\0\4\25\2\0\23\25\1\226\4\25"+
    "\27\0\2\25\4\0\4\25\2\0\23\25\1\227\4\25"+
    "\27\0\2\25\4\0\4\25\2\0\1\230\27\25\27\0"+
    "\2\25\4\0\4\25\2\0\24\25\1\231\3\25\27\0"+
    "\2\25\4\0\4\25\2\0\21\25\1\232\6\25\27\0"+
    "\2\25\4\0\4\25\2\0\15\25\1\233\12\25\27\0"+
    "\2\25\4\0\4\25\2\0\3\25\1\234\24\25\27\0"+
    "\2\25\4\0\4\25\2\0\5\25\1\235\22\25\6\0"+
    "\16\124\1\236\54\124\21\0\2\25\4\0\4\25\2\0"+
    "\15\25\1\237\12\25\27\0\2\25\4\0\4\25\2\0"+
    "\1\25\1\240\26\25\27\0\2\25\4\0\4\25\2\0"+
    "\13\25\1\241\14\25\27\0\2\25\4\0\4\25\2\0"+
    "\23\25\1\242\4\25\27\0\2\25\4\0\4\25\2\0"+
    "\10\25\1\243\17\25\27\0\2\25\4\0\4\25\2\0"+
    "\23\25\1\244\4\25\27\0\2\25\4\0\4\25\2\0"+
    "\1\25\1\245\26\25\27\0\2\25\4\0\4\25\2\0"+
    "\15\25\1\246\12\25\27\0\2\25\4\0\4\25\2\0"+
    "\7\25\1\247\20\25\27\0\2\25\4\0\4\25\2\0"+
    "\10\25\1\250\17\25\6\0\16\124\1\236\50\124\1\251"+
    "\3\124\21\0\2\25\4\0\4\25\2\0\1\252\27\25"+
    "\27\0\2\25\4\0\4\25\2\0\15\25\1\253\12\25"+
    "\27\0\2\25\4\0\4\25\2\0\23\25\1\254\4\25"+
    "\27\0\2\25\4\0\4\25\2\0\5\25\1\255\22\25"+
    "\27\0\2\25\4\0\4\25\2\0\5\25\1\256\22\25"+
    "\27\0\2\25\4\0\4\25\2\0\13\25\1\257\14\25"+
    "\27\0\2\25\4\0\4\25\2\0\1\260\27\25\27\0"+
    "\2\25\4\0\4\25\2\0\21\25\1\261\6\25\27\0"+
    "\2\25\4\0\4\25\2\0\1\262\27\25\27\0\2\25"+
    "\4\0\4\25\2\0\23\25\1\263\4\25\27\0\2\25"+
    "\4\0\4\25\2\0\5\25\1\264\22\25\6\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[7552];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\1\1\3\11\1\1\1\11"+
    "\1\1\1\11\1\1\1\11\5\1\1\11\3\1\1\11"+
    "\17\1\1\11\1\1\1\11\1\0\1\11\3\0\2\11"+
    "\3\0\5\11\32\1\1\0\2\11\1\1\1\11\2\1"+
    "\1\0\30\1\1\0\27\1\1\0\1\11\20\1\1\0"+
    "\26\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[180];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */

// TokenInfo es una estructura interna para guardar la informacion
// de cada token que se va reconociendo durante el analisis lexico.
// Almacena el tipo de token, el texto original, y su posicion en el archivo.
private static class TokenInfo {
    String token;
    String lexema;
    int linea;
    int columna;
    TokenInfo(String token, String lexema, int linea, int columna) {
        this.token = token;
        this.lexema = lexema;
        this.linea = linea;
        this.columna = columna;
    }
}

// Lista donde se van acumulando todos los tokens reconocidos durante el analisis.
private List<TokenInfo> tokenLog = new ArrayList<>();

// Permite que otras clases consulten la lista de tokens si lo necesitan.
public List<TokenInfo> getTokenLog() {
    return tokenLog;
}

// Registra un token que no tiene lexema relevante (como operadores o palabras reservadas).
// Entrada: nombre del token.
private void addToken(String token) {
    tokenLog.add(new TokenInfo(token, "-", yyline + 1, yycolumn));
}

// Registra un token junto con su lexema (como identificadores o literales).
// Entrada: nombre del token y el texto reconocido.
private void addToken(String token, String lexema) {
    tokenLog.add(new TokenInfo(token, lexema, yyline + 1, yycolumn));
}

// Escribe todos los tokens reconocidos en un archivo de texto con formato de tabla.
// Para los identificadores y MAIN, consulta la tabla de simbolos para incluir el scope.
// Entrada : ruta del archivo de salida y el manejador de la tabla de simbolos.
// Salida  : archivo tokens.txt con la lista completa de tokens.
public void exportarTokens(String ruta, tabla.TablaManagement tablaManager) {
    try (PrintWriter writer = new PrintWriter(new FileWriter(ruta))) {
        writer.println("           LISTA DE TOKENS            ");
        writer.printf("%-12s %-15s %-8s %-8s %-15s%n",
                "TOKEN", "LEXEMA", "LINEA", "COL", "SCOPE/INFO");
        for (TokenInfo t : tokenLog) {
            // Por defecto no hay informacion de scope disponible.
            String extraInfo = "N/A";

            // Si el token es un identificador o MAIN, se busca en la tabla de simbolos
            // para saber en que scope fue declarado.
            if (t.token.equals("ID") || t.token.equals("MAIN")) {
                if (tablaManager != null) {
                    tabla.Simbolo sim = tablaManager.buscarEnHistorial(t.lexema);
                    if (sim != null) {
                        extraInfo = "Scope " + sim.getScope();
                    } else {
                        // El identificador aparece pero aun no fue declarado formalmente.
                        extraInfo = "Scope (Pendiente)";
                    }
                }
            }
            writer.printf("%-12s %-15s %-8d %-8d %-15s%n",
                    t.token,
                    t.lexema,
                    t.linea,
                    t.columna,
                    extraInfo);
        }
        System.out.println("Tokens exportados correctamente a: " + ruta);
    } catch (IOException e) {
        System.err.println("Error al exportar tokens: " + e.getMessage());
    }
}

// Recorre la lista de tokens buscando los que fueron marcados como errores lexicos
// y los escribe en un archivo separado para facilitar su revision.
// Entrada : ruta del archivo de salida.
// Salida  : archivo con los errores lexicos encontrados, o un mensaje indicando que no hubo ninguno.
public void exportarErroresLexicos(String ruta) {
    try (PrintWriter writer = new PrintWriter(new FileWriter(ruta))) {
        boolean hayErrores = false;
        for (TokenInfo t : tokenLog) {
            if (t.token.equals("LEX_ERROR")) {
                writer.printf("ERROR LEXICO -> Linea %d, Columna %d, Caracter: '%s'%n", 
                        t.linea, t.columna, t.lexema);
                hayErrores = true;
            }
        }
        if (!hayErrores) {
            writer.println("No se detectaron errores lexicos.");
        }
        System.out.println("Errores lexicos exportados a: " + ruta);
    } catch (IOException e) {
        System.err.println("Error al exportar errores lexicos: " + e.getMessage());
    }
}

// Retorna el numero de linea actual donde esta leyendo el lexer.
// Se suma 1 porque JFlex comienza a contar desde 0.
public int getCurrentLine() {
    return yyline + 1;
}

// Retorna el numero de columna actual donde esta leyendo el lexer.
// Se suma 1 por la misma razon que getCurrentLine.
public int getCurrentColumn() {
    return yycolumn + 1;
}



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return new Symbol(sym.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { addToken("LEX_ERROR", yytext());
    System.err.println("ERROR LEXICO -> Linea " + (yyline+1) +
        ", Columna " + yycolumn +
        ", Caracter: '" + yytext() + "'");
    return new Symbol(sym.LEX_ERROR, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 61: break;
          case 2:
            { /* ignorar */
            }
          // fall through
          case 62: break;
          case 3:
            { addToken("PYC"); return new Symbol(sym.PYC, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 63: break;
          case 4:
            { addToken("OR"); return new Symbol(sym.OR, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 64: break;
          case 5:
            { addToken("NOT"); return new Symbol(sym.NOT, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 65: break;
          case 6:
            { addToken("MOD"); return new Symbol(sym.MOD, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 66: break;
          case 7:
            { addToken("MULT"); return new Symbol(sym.MULT, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 67: break;
          case 8:
            { addToken("PLUS"); return new Symbol(sym.PLUS, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 68: break;
          case 9:
            { addToken("COMMA"); return new Symbol(sym.COMMA, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 69: break;
          case 10:
            { addToken("MINUS"); return new Symbol(sym.MINUS, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 70: break;
          case 11:
            { addToken("DIV"); return new Symbol(sym.DIV, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 71: break;
          case 12:
            { addToken("INT_LIT", yytext()); return new Symbol(sym.INT_LIT, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 72: break;
          case 13:
            { addToken("DOSPUNTOS"); return new Symbol(sym.DOSPUNTOS, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 73: break;
          case 14:
            { addToken("AND"); return new Symbol(sym.AND, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 74: break;
          case 15:
            { addToken("ID", yytext()); return new Symbol(sym.ID, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 75: break;
          case 16:
            { addToken("POW"); return new Symbol(sym.POW, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 76: break;
          case 17:
            { addToken("SEP"); return new Symbol(sym.SEP, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 77: break;
          case 18:
            { /* ignorar BOM */
            }
          // fall through
          case 78: break;
          case 19:
            { String sinComillas = yytext().substring(1, yytext().length()-1);
    addToken("STRING_LIT", sinComillas);
    return new Symbol(sym.STRING_LIT, yyline+1, yycolumn, sinComillas);
            }
          // fall through
          case 79: break;
          case 20:
            { addToken("INC"); return new Symbol(sym.INC, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 80: break;
          case 21:
            { addToken("DEC"); return new Symbol(sym.DEC, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 81: break;
          case 22:
            { addToken("LLAVE_D"); return new Symbol(sym.LLAVE_D, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 82: break;
          case 23:
            { addToken("ASSIGN"); return new Symbol(sym.ASSIGN, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 83: break;
          case 24:
            { addToken("ARR_I"); return new Symbol(sym.ARR_I, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 84: break;
          case 25:
            { addToken("PAR_I"); return new Symbol(sym.PAR_I, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 85: break;
          case 26:
            { addToken("ARR_D"); return new Symbol(sym.ARR_D, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 86: break;
          case 27:
            { addToken("DO"); return new Symbol(sym.DO, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 87: break;
          case 28:
            { addToken("IF"); return new Symbol(sym.IF, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 88: break;
          case 29:
            { addToken("LLAVE_I"); return new Symbol(sym.LLAVE_I, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 89: break;
          case 30:
            { addToken("PAR_D"); return new Symbol(sym.PAR_D, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 90: break;
          case 31:
            { String sinComillas = yytext().substring(1, yytext().length()-1);
    addToken("CHAR_LIT", sinComillas);
    return new Symbol(sym.CHAR_LIT, yyline+1, yycolumn, sinComillas);
            }
          // fall through
          case 91: break;
          case 32:
            { addToken("FLOAT_LIT", yytext()); return new Symbol(sym.FLOAT_LIT, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 92: break;
          case 33:
            { addToken("EXPINT_LIT", yytext()); return new Symbol(sym.EXPINT_LIT, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 93: break;
          case 34:
            { addToken("CIN"); return new Symbol(sym.CIN, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 94: break;
          case 35:
            { addToken("INT"); return new Symbol(sym.INT, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 95: break;
          case 36:
            { addToken("FRAC_LIT", yytext()); return new Symbol(sym.FRAC_LIT, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 96: break;
          case 37:
            { addToken("TRUE"); return new Symbol(sym.TRUE, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 97: break;
          case 38:
            { addToken("BOOL"); return new Symbol(sym.BOOL, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 98: break;
          case 39:
            { addToken("CASE"); return new Symbol(sym.CASE, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 99: break;
          case 40:
            { addToken("CHAR"); return new Symbol(sym.CHAR, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 100: break;
          case 41:
            { addToken("COUT"); return new Symbol(sym.COUT, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 101: break;
          case 42:
            { addToken("ELSE"); return new Symbol(sym.ELSE, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 102: break;
          case 43:
            { addToken("FRAC_KW"); return new Symbol(sym.FRAC_KW, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 103: break;
          case 44:
            { addToken("FALSE"); return new Symbol(sym.FALSE, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 104: break;
          case 45:
            { addToken("BREAK"); return new Symbol(sym.BREAK, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 105: break;
          case 46:
            { addToken("EMPTY"); return new Symbol(sym.EMPTY, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 106: break;
          case 47:
            { addToken("EQUAL"); return new Symbol(sym.EQUAL, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 107: break;
          case 48:
            { addToken("FLOAT"); return new Symbol(sym.FLOAT, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 108: break;
          case 49:
            { addToken("WHILE"); return new Symbol(sym.WHILE, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 109: break;
          case 50:
            { addToken("EXPINT_KW"); return new Symbol(sym.EXPINT_KW, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 110: break;
          case 51:
            { addToken("LESS_T"); return new Symbol(sym.LESS_T, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 111: break;
          case 52:
            { addToken("RETURN"); return new Symbol(sym.RETURN, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 112: break;
          case 53:
            { addToken("STRING"); return new Symbol(sym.STRING, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 113: break;
          case 54:
            { addToken("SWITCH"); return new Symbol(sym.SWITCH, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 114: break;
          case 55:
            { addToken("DEFAULT"); return new Symbol(sym.DEFAULT, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 115: break;
          case 56:
            { addToken("LESS_TE"); return new Symbol(sym.LESS_TE, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 116: break;
          case 57:
            { addToken("N_EQUAL"); return new Symbol(sym.N_EQUAL, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 117: break;
          case 58:
            { addToken("MAIN", "__main__"); return new Symbol(sym.MAIN, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 118: break;
          case 59:
            { addToken("GREATER_T"); return new Symbol(sym.GREATER_T, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 119: break;
          case 60:
            { addToken("GREATER_TE"); return new Symbol(sym.GREATER_TE, yyline+1, yycolumn, yytext());
            }
          // fall through
          case 120: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
